export enum LmsErrorCode {
  TOPIC_NOT_FOUND = 'LMS_TOPIC_NOT_FOUND',
  LEVEL_NOT_FOUND = 'LMS_LEVEL_NOT_FOUND',
  LEVEL_LOCKED = 'LMS_LEVEL_LOCKED',
  INVALID_ATTEMPT_PAYLOAD = 'LMS_INVALID_ATTEMPT_PAYLOAD',
  COMPLETION_RULES_NOT_MET = 'LMS_COMPLETION_RULES_NOT_MET',
  CONTENT_NOT_FOUND = 'LMS_CONTENT_NOT_FOUND',
  QUESTION_NOT_FOUND = 'LMS_QUESTION_NOT_FOUND',
  ANALYTICS_NOT_FOUND = 'LMS_ANALYTICS_NOT_FOUND',
}

export type LmsLogEvent =
  | 'LMS_TOPIC_CREATED'
  | 'LMS_TOPIC_UPDATED'
  | 'LMS_TOPIC_DELETED'
  | 'LMS_LEVEL_COMPLETION'
  | 'LMS_VIDEO_PROGRESS'
  | 'LMS_QUIZ_ATTEMPT'
  | 'LMS_LEADERBOARD_FETCH'
  | 'LMS_ANALYTICS_FETCH';
